### PR TITLE
Create DoubeCherryGB-libretro

### PR DESCRIPTION
**Pull request by TimOelrichs**
w

### CODE REVIEW

**Comment by TimOelrichs** [comment]
want to add my liretro gameboy core 
https://github.com/TimOelrichs/doublecherryGB-libretro

**Comment by TimOelrichs** [comment]
upload doublecherry info

**Comment by hizzlekizzle** [comment]
Very cool! So netplay doesn't work automatically? I wouldn't figure you'd need to do anything special to get it working :/

**Comment by TimOelrichs** [comment]
thank you, appreciate it :) no netplay is not implemented yet. i need to serialize all gameboys and the dmg07/tetrishack states. so some work left to do, but doable :) so what's next? how to upload my repo to libretro? i didn't get the instruction on https://docs.libretro.com/development/cores/developing-cores/

**Comment by hizzlekizzle** [comment]
if you want to hand the repo over to the libretro org, you're welcome to do so, and we can make you an admin on it. This is totally optional, though. if you just want it to be built and distributed via the online updater, you just need a gitlab CI recipe in the top level of the repo (which you should already have left over from forking TGB-Dual repo) and then we need to add it to our list of repos to crawl. I believe @LibretroAdmin can help with this.

**Comment by RobLoach** [comment]
Looks like this is based off of https://github.com/libretro/tgbdual-libretro ? What are your plans with it? I'd recommend submitting your changes there as a Pull Request to the original repository, as TGB Dual could always do with some updates :wink:

**Comment by hizzlekizzle** [comment]
I didn't look too deeply into the changes, but my assumption was that it's too invasive to just add a setting onto TGB Dual.

**Comment by TimOelrichs** [comment]
@RobLoach Hi Rob, thanks for your assumption. For now I want to keep it a fork, for several reasons. I have some more cool features in the pipeline.  It's still wip and not very clean coded, but want to able to release features if I consider them playable. Right now, I have  to fix a Singleplayer bug, which prevents the core from starting if there ia no config file. And I am working on the netplay feature. If that's done. I want the core to be downloadble via the online-updater.

**Comment by TimOelrichs** [comment]
Okay, i got netplay working and updated my repo: https://github.com/TimOelrichs/doublecherryGB-libretro
@LibretroAdmin: Can you please add my repo to the online-updater, or tell me what i need to do? Thx in advance Tim

**Comment by RobLoach** [comment]
> Can you please add my repo to the online-updater

To get it added to the buildbot, it takes quite a bit of work. Need to add the repo to gitlab, set up the gitlab ci, go through testing across all platforms, etc. This is why I recommended adding it to the main repo :upside_down_face:

**Comment by hizzlekizzle** [comment]
yeah, that's a good point. getting to bypass all of the buildbot CI stuff would be nice.

**Comment by TimOelrichs** [comment]
So what do i have to do now? I'm still missing some instructions to make the core downloadable via Retroarch. And wouldn'd it be the same if i just merge into TGBDual? Doesn't the tests still have to pass? Are we talking about the same thing, when we're talking about the build-bot/onlineupdater? I just want the core to be downloadable. Why do i need it on gitlab? What are the rules and recipes for? Would it by enough if these recipes are done right? I am not working in the industry yet, so sorry if you have to explain some basics to me. If there was a good documentation i could read it by myself.  No offense ;-) Thanks in advance Tim

**Comment by hizzlekizzle** [comment]
The online updater is powered by a big, automated system that constantly fetches code from our hundreds of repos, compiles it for dozens of platforms and then hosts it for download by the client programs. We use Gitlab for that automated infrastructure, though Github is where our repos are officially hosted. The recipes are what tells the automated infrastructure how to do what it does.

By adding it to the existing TGB-Dual core, you would avoid having to create and test additional recipes, and you would avoid a major bottleneck in the form of us having to manually track the new repo. That is, everything is automated once it's in place, but someone has to manually get it all set up to begin with, and its only a couple of people on our team who have access to do that part, so it depends on them actually doing it.

**Comment by TimOelrichs** [comment]
Hello, any News here? Not on gitlab yet, isn't it? Thx in advance.

**Comment by LibretroAdmin** [comment]
@TimOelrichs Hi there

The repo is setup, however, you need to change something in your .gitlab-ci.yml file.

> CORENAME: tgbdual

This is wrong, and should be changed to:

> CORENAME: DoubleCherryGB

**Pull request merged**
