### PR TITLE
info: Update Vircon32 .info

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Review by RobLoach — COMMENTED** [review]
Vircon32 gave the :+1: in Discord

**Comment by vircon32** [comment]
I can give it here too 👍

**Comment by vircon32** [comment]
Hi @RobLoach since this was not merged in time, would you mind updating line 8 with the new core version? I just realized I should have updated this. The change is:
-display_version = "2023.08.24"
+display_version = "2024.04.14"
I would add the commit myself but looks like I don't have the needed permissions.

**Comment by vircon32** [comment]
Thank you :)

**Pull request merged**
