### PR TITLE
dosbox_core: Add to Linux armhf recipe

### PR DESCRIPTION
**Pull request by realnc**
It will download the build from github, no actual build is performed.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I know bparker was always really skeeved out about scripts downloading binaries from external sources because it can be used as an attack vector on the entire ecosystem just by compromising a single point of failure.

Is that something we should be concerned about here, as well?

**Comment by realnc** [comment]
It's an automated build done on GitHub's CI service, which runs on Azure. It then gets uploaded from the CI directly to https://github.com/realnc/dosbox-core/releases/tag/latest_build, which is where the buildbot will fetch it from.

I guess if Azure and GitHub get compromised in a way that alters binaries produced on Azure VMs, we're all screwed anyway :P

**Comment by hizzlekizzle** [comment]
heh, well, my thought was if they just compromised your repo and uploaded whatever and tagged it as the latest release.

**Comment by realnc** [comment]
Yes, if they compromise my account, they can do that. Are you suggesting that we remove these binary downloads from the buildbot? This is currently done for the two windows builds (x86 and x64) and the macos build.

**Comment by hizzlekizzle** [comment]
hmm, well, if the others are already like that, I'll go ahead and merge this one, too (esp since I probably merged the last ones), but I think we should probably discuss with the people who do the server administration whether this is how we want to handle it long-term.

Disclaimer: idgaf either way. I just know it's the same consideration that keeps us from having appimage builds already, so I figured it prudent to bring it up.

**Comment by realnc** [comment]
Even though I do have 2FA enabled on github, it's a valid concern. I think I can improve things by having the CI push the sha256 sums of the zip files into a branch that only contains these sums. When the buildbot downloads a build, the download make target can then check if the downloaded files match.

Let me see what I can come up with.

**Pull request merged**
