### PR TITLE
rename Spectravideo db, add new dbs, build PC-88 db

### PR DESCRIPTION
**Pull request by WizzardSK**

### CODE REVIEW

**Review by RobLoach — APPROVED** [review]
Thanks!

**Comment by WizzardSK** [comment]
Can we also please integrate https://github.com/WizzardSK/Spectravideo_-_SVI-318_-_SVI-328 into libretro?

**Comment by LibretroAdmin** [comment]
@RobLoach Let me know if this needs merging.

**Review by RobLoach — APPROVED** [review]
@LibretroAdmin Yeah, should be good. Thanks.

**Pull request merged**
