### PR TITLE
add LTO=true for Mesen

### PR DESCRIPTION
**Pull request by Tatsuya79**
Hope that works like this?

### CODE REVIEW

**Comment by twinaphex** [comment]
@fr500 Does this work?

**Comment by fr500** [comment]
It's built with MSVC LTO makes no difference there.
It only makes difference in the ming builds.

**Comment by fr500** [comment]
and no, the syntax is wrong extra arguments go towards the end of the line

**Comment by Tatsuya79** [comment]
ok, idk I'll just close that then.

**Pull request closed without merging**
