### PR TITLE
Added hiscore.dat to FBNeo firmware list

### PR DESCRIPTION
**Pull request by Sanaki**

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
@barbudreadmon any thoughts?

**Comment by Sanaki** [comment]
To be clear, this is in the FBNeo core repo and provides data to enable high score storage. The file itself isn't written in the process. It's a bios in the same sense as the BlastEm and Nestopia databases, which are also listed as firmware in their respective info files.

**Comment by barbudreadmon** [comment]
i don't mind

**Comment by hizzlekizzle** [comment]
k, thanks for the input. I'll go ahead and merge it, then :)

**Pull request merged**
