### PR TITLE
Add Nintendo prefix to Game & Watch

### PR DESCRIPTION
**Pull request by RobLoach**
From discussions at https://github.com/libretro/libretro-database/issues/330 .

@leiradel This okay with you?

### CODE REVIEW

**Comment by leiradel** [comment]
@RobLoach Well, there are games from a lot of manufacturers in there, but then again Game & Watch is a series of games by Nintendo so we may as well add the Nintendo prefix.

**Comment by RobLoach** [comment]
> then again Game & Watch is a series of games by Nintendo so we may as well add the Nintendo prefix.

Right, I believe that's the conclusion @lasers came to, from [looking at the Wikipedia article](https://en.wikipedia.org/wiki/Game_And_Watch). Seems reasonable.

**Comment by lasers** [comment]
This helps. http://nintendo.wikia.com/wiki/Game_&_Watch 
>A multiple of companies help Nintendo create their Game & Watch units, including Mego, CGL, Ji2l, Futuretronics, Bienegraeber&co, and Videopoche. While the games themselves were virtually unchanged, the box that the game came in were different as each one was custom made by the respective company.

**Comment by leiradel** [comment]
I believe it's talking about Nintendo partners that used to build and sell G&W games, but there are manufacturers totally unrelated to Nintendo that made their own LCD games: http://www.madrigaldesign.it/sim/download.php

But yes, I think it's ok to add the prefix.

**Pull request merged**
