### PR TITLE
Add Satellaview .bs as valid extension

### PR DESCRIPTION
**Pull request by ds22x**
Also added firmware info for BS-X.bin
This is for https://github.com/libretro/bsnes/pull/51

EDIT:
Despite what the commit title says, it adds .bs as a valid extension, not .bg.

### CODE REVIEW

**Comment by Sanaki** [comment]
If you want, you can `git commit --amend` to fix the commit description, then `git push --force` to update the remote version. I would also suggest including in the commit title that it's for the bsnes core, to make the commit history easier to understand.

**Comment by ds22x** [comment]
Thank you very much for the tip.

**Review by Sanaki — APPROVED** [review]
Based on the assumption that libretro/bsnes#51 is merged, everything here looks good.

**Comment by twinaphex** [comment]
Thanks again @ds22x .

**Comment by ds22x** [comment]
No problem.
Glad I could help.

**Pull request merged**
