### PR TITLE
Fix Gearboy info file

### PR DESCRIPTION
**Pull request by hyarsan**
This also adds all of the file extensions that Gearboy actually supports.

### CODE REVIEW

**Comment by orbea** [comment]
What editor are you using? One minor nitpick, your editor is screwing up the newline at the end of the file... Can you teach your editor to not do that? :)

**Comment by hyarsan** [comment]
Me: Hey Notepad++! Stop putting new lines at the end of files!
Notepad++: I am not sure how to do that...
Me: **google searches**
Me: **realizes that it's me who keeps doing that**

So what is the standard for new lines?

**Comment by hyarsan** [comment]
Turns out it was the Citra core info file only, whew. https://github.com/libretro/libretro-super/blob/master/dist/info/citra_libretro.info I don't know how to rebase, so can this be merged already?
The way I rebase is by deleting and reforking my fork which means that this pull request gets lost, I think.

**Comment by orbea** [comment]
It wasn't really a big deal, just it adds extra noise to the commits if they change back and forth all the time.

I don't have the power to merge this, but if you want to rebase you really should make commits in branches other than `master`, but here are some instructions on how you have rebase.
```
git remote add upstream https://github.com/libretro/libretro-super/
git fetch upstream
git rebase -i upstream/master # Will open up an interactive git window where you can tell it to change your commits. If no changes are need just save and exit the editor.
git push --force origin master # Force push to your `master` branch
```
In the future I suggest you make changes like this.
```
git clone https://github.com/hyarsan/libretro-super/
cd libretro-super
git checkout -b your_new_branch
# make your changes
git push origin your_new_branch
# make a PR
```
I hope this helps?

**Comment by orbea** [comment]
It wasn't really a big deal, just it adds extra noise to the commits if they change back and forth all the time.

I don't have the power to merge this, but if you want to rebase you really should make commits in branches other than master, but here are some instructions on how you have rebase.
```
git remote add upstream https://github.com/libretro/libretro-super/
git fetch upstream
git rebase -i upstream/master # Will open up an interactive git window where you can tell it to change your commits. If no changes are need just save and exit the editor.
git push --force origin master # Force push to your `master` branch
```
In the future I suggest you make changes like this.
```
git clone https://github.com/hyarsan/libretro-super/
cd libretro-super
git checkout -b your_new_branch
# make your changes
git add .
git commit -m "Your commit message"
git push origin your_new_branch
# make a PR
```
I hope this helps?

**Comment by hyarsan** [comment]
I will try that, thanks!

**Pull request merged**
