### PR TITLE
Add fb_alpha_new to Android build list

### PR DESCRIPTION
**Pull request by diablodiab**
Use the new JNI files

### CODE REVIEW

**Comment by fr500** [comment]
hmmm actually these aren't used at all

**Comment by diablodiab** [comment]
libretro-build-android-mk.sh is not the script that contains the list of Android cores being built by the buildbot ?

**Comment by diablodiab** [comment]
Oh I think I see. It's cores-android-jni, right? Under recipes for android ?

**Comment by fr500** [comment]
no, for jni cores it would be this:
https://github.com/libretro/libretro-super/blob/master/recipes/android/cores-android-jni

Example:
fb_alpha libretro-fba https://github.com/libretro/fba-libretro.git PROJECT YES GENERIC_JNI makefile.libretro svn-current/trunk/projectfiles/libretro-android/jni 

CORE_NAME FOLDER URL PROJECT|SUBMODULE|BRANCHE ENABLE JOB_TYPE MAKEFILE_NAME MAKIEFILE_LOCATION

So, important things here:
- CORE_NAME is the name of the build product, in this case fba_libretro
- FOLDER just the folder for the local clone, libretro-fba_new should do the trick
- URL
- PROJECT most of the time
- ENABLE would be YES
- GENERIC_JNI

The rest should be self explanatory, just make sure to include a trailing space always.
If you have problems I can do it but it's good to get other people involved.

**Comment by diablodiab** [comment]
Does it still make sense to keep the changes I made to libretro-build-android-mk.sh ?

**Comment by diablodiab** [comment]
Updated cores-android-jni as well now. I assume that it is okay to have libretro-build-android-mk.sh updated so you can compile it that way also.

**Comment by fr500** [comment]
yeah it would be fine I guess

**Pull request merged**
